IF 
(
  TEST-PATH -PATH "C:\USERS\EF296\DEVELOP\COMPRESS\PROJECT" -PATHTYPE ANY
)
{
  REMOVE-ITEM -PATH "C:\USERS\EF296\DEVELOP\COMPRESS\PROJECT" -RECURSE -FORCE
}
IF 
(
  TEST-PATH -PATH "C:\USERS\EF296\DEVELOP\COMPRESS\PROJECT.ZIP" -PATHTYPE ANY
)
{
  REMOVE-ITEM -PATH "C:\USERS\EF296\DEVELOP\COMPRESS\PROJECT.ZIP" -FORCE
}
ROBOCOPY "C:\USERS\EF296\DEVELOP\PROJECT" "C:\USERS\EF296\DEVELOP\COMPRESS\PROJECT" /S /XF /XD DIRS "AAB" "NODE_MODULES"
$VAR1 = @{
  PATH = "C:\USERS\EF296\DEVELOP\COMPRESS\PROJECT"
  COMPRESSIONLEVEL = "FASTEST"
  DESTINATIONPATH = "C:\USERS\EF296\DEVELOP\COMPRESS\PROJECT.ZIP"
}
COMPRESS-ARCHIVE @VAR1
